"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-08 20:19:00.111557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS alejandra'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estatus', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='alejandra'
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grado', sa.String(length=1), nullable=False),
    sa.Column('grupo', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='alejandra'
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='alejandra'
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol'),
    schema='alejandra'
    )
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname_p', sa.String(length=50), nullable=False),
    sa.Column('lastname_m', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('codigo_qr', sa.String(length=255), nullable=True),
    sa.Column('codigo_barras', sa.String(length=255), nullable=True),
    sa.Column('pass', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['alejandra.grupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('codigo_qr'),
    schema='alejandra'
    )
    op.create_table('grupos_materias',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['alejandra.grupos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['alejandra.materias.id'], ),
    sa.PrimaryKeyConstraint('grupo_id', 'materia_id'),
    schema='alejandra'
    )
    op.create_table('historial_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=False),
    sa.Column('registro_afectado_id', sa.Integer(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('fecha_accion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['alejandra.docentes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alejandra'
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('salon', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['alejandra.docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['alejandra.materias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alejandra'
    )
    op.create_table('materias_docentes',
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['alejandra.docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['alejandra.materias.id'], ),
    sa.PrimaryKeyConstraint('docente_id', 'materia_id'),
    schema='alejandra'
    )
    op.create_table('anotaciones_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alejandra.alumnos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['alejandra.docentes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alejandra'
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumnos_id', sa.Integer(), nullable=False),
    sa.Column('español', sa.Numeric(), nullable=True),
    sa.Column('matematicas', sa.Numeric(), nullable=True),
    sa.Column('ciencias', sa.Numeric(), nullable=True),
    sa.Column('geografia', sa.Numeric(), nullable=True),
    sa.Column('historia', sa.Numeric(), nullable=True),
    sa.Column('f_civica', sa.Numeric(), nullable=True),
    sa.Column('ingles', sa.Numeric(), nullable=True),
    sa.Column('artes', sa.Numeric(), nullable=True),
    sa.Column('f_español', sa.Numeric(), nullable=True),
    sa.Column('f_matematicas', sa.Numeric(), nullable=True),
    sa.Column('tecnologia', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['alumnos_id'], ['alejandra.alumnos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alejandra'
    )
    op.create_table('calificaciones_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumnos_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumnos_id'], ['alejandra.alumnos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['alejandra.materias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alejandra'
    )
    # ### end Alembic commands ###

    # ── Seed: catálogo de roles (fuente de verdad del login) ───────────
    op.get_bind().execute(sa.text("""
        INSERT INTO alejandra.rol (id, rol) VALUES (1, 'admin'), (2, 'docente')
        ON CONFLICT (id) DO NOTHING
    """))

    # ── Seed: materias por defecto del plantel ──────────────────────────
    materias = [
        ('Español', 'Lengua y literatura'),
        ('Matemáticas', 'Matemáticas'),
        ('Biología', 'Biología'),
        ('Química', 'Química'),
        ('Física', 'Física'),
        ('Historia', 'Historia'),
        ('Formación cívica y Ética', 'Formación cívica y Ética'),
        ('Geografía', 'Geografía'),
        ('Inglés', 'Inglés'),
        ('Artes (música y teatro)', 'Artes: música y teatro'),
        ('Tecnologías (talleres)', 'Tecnologías: talleres'),
        ('Fomento a la lectura', 'Fomento a la lectura'),
        ('Educación Física', 'Educación Física'),
    ]
    bind = op.get_bind()
    for nombre, descripcion in materias:
        bind.execute(sa.text("""
            INSERT INTO alejandra.materias (nombre, descripcion)
            VALUES (:nombre, :descripcion)
            ON CONFLICT (nombre) DO NOTHING
        """), {'nombre': nombre, 'descripcion': descripcion})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificaciones_materia', schema='alejandra')
    op.drop_table('calificaciones', schema='alejandra')
    op.drop_table('anotaciones_alumno', schema='alejandra')
    op.drop_table('materias_docentes', schema='alejandra')
    op.drop_table('horarios', schema='alejandra')
    op.drop_table('historial_logs', schema='alejandra')
    op.drop_table('grupos_materias', schema='alejandra')
    op.drop_table('alumnos', schema='alejandra')
    op.drop_table('rol', schema='alejandra')
    op.drop_table('materias', schema='alejandra')
    op.drop_table('grupos', schema='alejandra')
    op.drop_table('docentes', schema='alejandra')
    # ### end Alembic commands ###
