"""add qr support and auth tables

Revision ID: 039e35968cbc
Revises: 
Create Date: 2026-07-26 01:22:16.598105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039e35968cbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'alejandra'
              AND table_name = 'alumnos'
              AND column_name = 'codigo_qr'
        ) THEN
            ALTER TABLE alejandra.alumnos ADD COLUMN codigo_qr VARCHAR(255);
        END IF;
    END $$;
    """)

    with op.batch_alter_table('historial_logs', schema='alejandra') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_historial_docente'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'docentes', ['docente_id'], ['id'], referent_schema='alejandra')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'alejandra'
              AND table_name = 'alumnos'
              AND column_name = 'codigo_qr'
        ) THEN
            ALTER TABLE alejandra.alumnos DROP COLUMN codigo_qr;
        END IF;
    END $$;
    """)

    with op.batch_alter_table('historial_logs', schema='alejandra') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_historial_docente'), 'docentes', ['docente_id'], ['id'], referent_schema='alejandra', ondelete='SET NULL')

    # ### end Alembic commands ###
